import type { SettingsSection, CategoryInfo } from "../types/newTypes";

export const settingsSections: SettingsSection[] = [
  // Account Settings
  {
    id: "profile",
    title: "Personal Profile",
    icon: "👤",
    description:
      "Manage your personal information, avatar, and basic account details",
    category: "account",
    searchTerms: [
      "profile",
      "name",
      "email",
      "avatar",
      "personal",
      "user",
      "account",
    ],
  },
  {
    id: "subscription",
    title: "Subscription & Billing",
    icon: "💳",
    description:
      "View your subscription plan, usage limits, and billing information",
    category: "account",
    searchTerms: [
      "subscription",
      "billing",
      "payment",
      "plan",
      "upgrade",
      "pro",
      "enterprise",
    ],
  },
  {
    id: "notifications",
    title: "Notifications",
    icon: "🔔",
    description: "Configure email, push, and in-app notification preferences",
    category: "account",
    searchTerms: [
      "notifications",
      "alerts",
      "email",
      "push",
      "messages",
      "sounds",
    ],
  },
  {
    id: "privacy",
    title: "Privacy & Data",
    icon: "🛡️",
    description: "Control your privacy settings and data sharing preferences",
    category: "account",
    searchTerms: [
      "privacy",
      "data",
      "sharing",
      "analytics",
      "tracking",
      "personal",
    ],
  },

  // Appearance Settings
  {
    id: "themes",
    title: "Themes & Appearance",
    icon: "🎨",
    description:
      "Customize your interface with beautiful themes and visual styles",
    category: "appearance",
    searchTerms: [
      "theme",
      "dark",
      "light",
      "color",
      "appearance",
      "visual",
      "style",
    ],
  },
  {
    id: "display",
    title: "Display Settings",
    icon: "🖥️",
    description: "Adjust font size, layout density, and display preferences",
    category: "appearance",
    searchTerms: [
      "display",
      "font",
      "size",
      "zoom",
      "layout",
      "density",
      "screen",
    ],
  },
  {
    id: "accessibility",
    title: "Accessibility",
    icon: "♿",
    description: "Configure accessibility features for better usability",
    category: "appearance",
    searchTerms: [
      "accessibility",
      "a11y",
      "screen reader",
      "contrast",
      "keyboard",
      "vision",
    ],
  },

  // AI Models Settings
  {
    id: "ai-providers",
    title: "AI Model Providers",
    icon: "🤖",
    description:
      "Configure OpenAI, Anthropic, Google, and other AI model providers",
    category: "ai-models",
    searchTerms: [
      "ai",
      "models",
      "openai",
      "anthropic",
      "google",
      "claude",
      "gpt",
      "providers",
    ],
  },
  {
    id: "model-settings",
    title: "Model Configuration",
    icon: "⚙️",
    description:
      "Set model parameters like temperature, max tokens, and system prompts",
    category: "ai-models",
    searchTerms: [
      "temperature",
      "tokens",
      "prompts",
      "parameters",
      "config",
      "tuning",
    ],
  },
  {
    id: "rate-limits",
    title: "Rate Limits & Usage",
    icon: "📊",
    description: "Monitor and configure API rate limits and usage quotas",
    category: "ai-models",
    searchTerms: [
      "rate",
      "limits",
      "quota",
      "usage",
      "api",
      "calls",
      "monitoring",
    ],
  },

  // Security Settings
  {
    id: "authentication",
    title: "Authentication",
    icon: "🔐",
    description:
      "Manage passwords, two-factor authentication, and login security",
    category: "security",
    searchTerms: [
      "password",
      "2fa",
      "authentication",
      "login",
      "security",
      "two-factor",
    ],
  },
  {
    id: "api-keys",
    title: "API Keys & Tokens",
    icon: "🔑",
    description: "Generate and manage API keys for external integrations",
    category: "security",
    searchTerms: [
      "api",
      "keys",
      "tokens",
      "authentication",
      "integration",
      "access",
    ],
  },
  {
    id: "session-management",
    title: "Session Management",
    icon: "⏰",
    description: "Configure session timeouts and device management",
    category: "security",
    searchTerms: [
      "session",
      "timeout",
      "devices",
      "logout",
      "idle",
      "activity",
    ],
  },
  {
    id: "audit-logs",
    title: "Security Audit",
    icon: "📋",
    description: "View login history, security events, and audit logs",
    category: "security",
    searchTerms: ["audit", "logs", "history", "security", "events", "activity"],
  },

  // Automation Settings
  {
    id: "workflows",
    title: "Automation Workflows",
    icon: "🔄",
    description: "Create and manage automated workflows and triggers",
    category: "automation",
    searchTerms: [
      "automation",
      "workflows",
      "triggers",
      "actions",
      "rules",
      "auto",
    ],
  },
  {
    id: "scheduled-tasks",
    title: "Scheduled Tasks",
    icon: "⏱️",
    description: "Set up recurring tasks and scheduled operations",
    category: "automation",
    searchTerms: [
      "schedule",
      "tasks",
      "recurring",
      "cron",
      "timer",
      "periodic",
    ],
  },
  {
    id: "webhooks",
    title: "Webhooks & Events",
    icon: "📡",
    description: "Configure webhooks and event-driven automations",
    category: "automation",
    searchTerms: [
      "webhooks",
      "events",
      "callbacks",
      "http",
      "notifications",
      "triggers",
    ],
  },

  // Integrations Settings
  {
    id: "slack-integration",
    title: "Slack Integration",
    icon: "💬",
    description: "Connect and configure Slack for team collaboration",
    category: "integrations",
    searchTerms: [
      "slack",
      "chat",
      "team",
      "collaboration",
      "messages",
      "channels",
    ],
  },
  {
    id: "github-integration",
    title: "GitHub Integration",
    icon: "🐙",
    description: "Integrate with GitHub for repository management and CI/CD",
    category: "integrations",
    searchTerms: [
      "github",
      "git",
      "repository",
      "code",
      "version control",
      "ci/cd",
    ],
  },
  {
    id: "google-workspace",
    title: "Google Workspace",
    icon: "📊",
    description: "Connect Google Drive, Sheets, Docs, and other G Suite apps",
    category: "integrations",
    searchTerms: [
      "google",
      "drive",
      "sheets",
      "docs",
      "gmail",
      "workspace",
      "gsuite",
    ],
  },
  {
    id: "microsoft-365",
    title: "Microsoft 365",
    icon: "📧",
    description: "Integrate with Office 365, Teams, and OneDrive",
    category: "integrations",
    searchTerms: [
      "microsoft",
      "office",
      "365",
      "teams",
      "onedrive",
      "outlook",
      "excel",
    ],
  },
  {
    id: "database-connections",
    title: "Database Connections",
    icon: "🗄️",
    description:
      "Configure connections to MySQL, PostgreSQL, MongoDB, and more",
    category: "integrations",
    searchTerms: [
      "database",
      "mysql",
      "postgresql",
      "mongodb",
      "sql",
      "connection",
    ],
  },

  // Advanced Settings
  {
    id: "developer-mode",
    title: "Developer Mode",
    icon: "👨‍💻",
    description: "Enable advanced features for developers and power users",
    category: "advanced",
    searchTerms: [
      "developer",
      "debug",
      "advanced",
      "console",
      "logs",
      "debugging",
    ],
  },
  {
    id: "performance",
    title: "Performance Tuning",
    icon: "⚡",
    description: "Optimize memory usage, caching, and performance settings",
    category: "advanced",
    searchTerms: [
      "performance",
      "memory",
      "cache",
      "optimization",
      "speed",
      "tuning",
    ],
  },
  {
    id: "backup-restore",
    title: "Backup & Restore",
    icon: "💾",
    description: "Configure automatic backups and data restoration options",
    category: "advanced",
    searchTerms: ["backup", "restore", "export", "import", "data", "recovery"],
  },
  {
    id: "experimental",
    title: "Experimental Features",
    icon: "🧪",
    description: "Try beta features and experimental functionality",
    category: "advanced",
    searchTerms: [
      "experimental",
      "beta",
      "preview",
      "features",
      "testing",
      "new",
    ],
    beta: true,
  },
];

export const categories: CategoryInfo[] = [
  {
    id: "all",
    title: "All Settings",
    icon: "⚙️",
    description: "Browse all available settings",
    count: settingsSections.length,
    color: "#667eea",
  },
  {
    id: "account",
    title: "Account",
    icon: "👤",
    description: "Personal profile and account management",
    count: settingsSections.filter((s) => s.category === "account").length,
    color: "#667eea",
  },
  {
    id: "appearance",
    title: "Appearance",
    icon: "🎨",
    description: "Themes, display, and visual customization",
    count: settingsSections.filter((s) => s.category === "appearance").length,
    color: "#e74c3c",
  },
  {
    id: "ai-models",
    title: "AI Models",
    icon: "🤖",
    description: "AI provider configuration and model settings",
    count: settingsSections.filter((s) => s.category === "ai-models").length,
    color: "#27ae60",
  },
  {
    id: "security",
    title: "Security",
    icon: "🔐",
    description: "Authentication, keys, and security features",
    count: settingsSections.filter((s) => s.category === "security").length,
    color: "#f39c12",
  },
  {
    id: "automation",
    title: "Automation",
    icon: "🔄",
    description: "Workflows, triggers, and automated tasks",
    count: settingsSections.filter((s) => s.category === "automation").length,
    color: "#9b59b6",
  },
  {
    id: "integrations",
    title: "Integrations",
    icon: "🔌",
    description: "Third-party services and platform connections",
    count: settingsSections.filter((s) => s.category === "integrations").length,
    color: "#3498db",
  },
  {
    id: "advanced",
    title: "Advanced",
    icon: "⚡",
    description: "Developer tools and advanced configuration",
    count: settingsSections.filter((s) => s.category === "advanced").length,
    color: "#34495e",
  },
];
